flags: {}
extra-package-dbs: []
packages:
- '.'
- location: /home/frank/Workspace8/repo8/uniform/uniform-strings
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-convenience
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-algebras
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-error
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-fileio
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-time
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-http

extra-deps: []
resolver: lts-8.13
